/**
 * Zentrale Registry aller Fehler-Codes, die die API in Exception-Response-
 * Bodies mitschickt (zusätzlich zum bisherigen `message`-Feld, siehe
 * AppException). Das Frontend (separates Repo, fleettrack-app) übersetzt
 * diese Codes in `messages/{de,en,fr,it}.json` unter dem Namespace `errors` -
 * die Keys dort MÜSSEN exakt diesen String-Werten entsprechen.
 *
 * Ein Code steht für einen *logischen* Fehler, nicht für eine Code-Zeile -
 * mehrere `throw`-Stellen mit identischer Bedeutung teilen sich einen Code.
 * `GENERIC_*`-Codes bündeln Guard-/Interna-Fehler, die ein Nutzer über die
 * normale UI praktisch nie auslösen kann (siehe Plan "Backend-Fehlermeldungen
 * viersprachig machen").
 */
export const ErrorCode = {
  // --- Generische Buckets (Guards/Interna, selten user-sichtbar) ---
  VALIDATION_BAD_REQUEST_GENERIC: 'VALIDATION_BAD_REQUEST_GENERIC',
  AUTH_FORBIDDEN_GENERIC: 'AUTH_FORBIDDEN_GENERIC',
  AUTH_UNAUTHORIZED_GENERIC: 'AUTH_UNAUTHORIZED_GENERIC',
  INTERNAL_ERROR_GENERIC: 'INTERNAL_ERROR_GENERIC',

  // --- Auth (Login/Signup/Token, inkl. übersetzte Supabase-SDK-Fehler) ---
  AUTH_EMAIL_NOT_CONFIRMED: 'AUTH_EMAIL_NOT_CONFIRMED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_ALREADY_REGISTERED: 'AUTH_USER_ALREADY_REGISTERED',
  AUTH_PASSWORD_TOO_SHORT: 'AUTH_PASSWORD_TOO_SHORT',
  AUTH_INVALID_EMAIL: 'AUTH_INVALID_EMAIL',
  AUTH_SIGNUP_INVALID_PASSWORD: 'AUTH_SIGNUP_INVALID_PASSWORD',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_EMAIL_RATE_LIMIT: 'AUTH_EMAIL_RATE_LIMIT',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_GENERIC_ERROR: 'AUTH_GENERIC_ERROR',
  AUTH_RESET_PASSWORD_FORBIDDEN: 'AUTH_RESET_PASSWORD_FORBIDDEN',
  AUTH_INVALID_USER: 'AUTH_INVALID_USER',
  AUTH_MISSING_HEADER: 'AUTH_MISSING_HEADER',
  AUTH_TOKEN_VERIFICATION_FAILED: 'AUTH_TOKEN_VERIFICATION_FAILED',
  AUTH_PROFILE_CONFLICT: 'AUTH_PROFILE_CONFLICT',
  AUTH_PROFILE_LOAD_FAILED: 'AUTH_PROFILE_LOAD_FAILED',

  // --- Fahrzeuge ---
  VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
  VEHICLE_NOT_IN_YOUR_ORG: 'VEHICLE_NOT_IN_YOUR_ORG',
  VEHICLE_LIMIT_REACHED: 'VEHICLE_LIMIT_REACHED',
  ORG_VEHICLE_MANAGE_FORBIDDEN: 'ORG_VEHICLE_MANAGE_FORBIDDEN',

  // --- Nutzungen (Usages) ---
  USAGE_NOT_FOUND: 'USAGE_NOT_FOUND',
  USAGE_DELETE_FORBIDDEN: 'USAGE_DELETE_FORBIDDEN',
  USAGE_EDIT_FORBIDDEN: 'USAGE_EDIT_FORBIDDEN',
  ORG_NO_MEMBERSHIP: 'ORG_NO_MEMBERSHIP',

  // --- Organisationen (Zugriff/Verwaltung) ---
  ORG_NOT_MEMBER_OF_TARGET: 'ORG_NOT_MEMBER_OF_TARGET',
  ORG_NOT_MANAGER: 'ORG_NOT_MANAGER',
  ORG_ID_AMBIGUOUS: 'ORG_ID_AMBIGUOUS',
  ORG_INVITE_MANAGE_FORBIDDEN: 'ORG_INVITE_MANAGE_FORBIDDEN',
  ORG_VIEW_FORBIDDEN: 'ORG_VIEW_FORBIDDEN',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  ORG_NAME_TAKEN: 'ORG_NAME_TAKEN',
  ORG_NAME_TAKEN_AFTER_PAYMENT: 'ORG_NAME_TAKEN_AFTER_PAYMENT',
  ORG_LOGO_INVALID: 'ORG_LOGO_INVALID',

  // --- Mitglieder/Rollen ---
  MEMBER_ROLE_OWNER_VIA_TRANSFER_ONLY: 'MEMBER_ROLE_OWNER_VIA_TRANSFER_ONLY',
  MEMBER_DEMOTE_FORBIDDEN: 'MEMBER_DEMOTE_FORBIDDEN',
  MEMBER_ALREADY_OWNER: 'MEMBER_ALREADY_OWNER',
  MEMBER_CURRENT_OWNER_NOT_FOUND: 'MEMBER_CURRENT_OWNER_NOT_FOUND',
  MEMBER_TARGET_NOT_FOUND: 'MEMBER_TARGET_NOT_FOUND',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  MEMBER_LAST_OWNER: 'MEMBER_LAST_OWNER',
  MEMBER_LIMIT_REACHED: 'MEMBER_LIMIT_REACHED',

  // --- Einladungen (Invites) ---
  INVITE_ORGANIZATION_NOT_FOUND: 'INVITE_ORGANIZATION_NOT_FOUND',
  ORGANIZATION_INACTIVE: 'ORGANIZATION_INACTIVE',
  INVITE_ALREADY_EXISTS: 'INVITE_ALREADY_EXISTS',
  INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
  INVITE_ALREADY_USED: 'INVITE_ALREADY_USED',
  INVITE_EXPIRED: 'INVITE_EXPIRED',
  INVITE_EMAIL_MISMATCH: 'INVITE_EMAIL_MISMATCH',
  INVITE_DELETE_FORBIDDEN: 'INVITE_DELETE_FORBIDDEN',
  INVITE_ACCEPT_EMAIL_MISMATCH: 'INVITE_ACCEPT_EMAIL_MISMATCH',

  // --- Subscription/Billing ---
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  SUBSCRIPTION_NO_STRIPE_SUBSCRIPTION: 'SUBSCRIPTION_NO_STRIPE_SUBSCRIPTION',
  SUBSCRIPTION_NO_STRIPE_CUSTOMER: 'SUBSCRIPTION_NO_STRIPE_CUSTOMER',
  SUBSCRIPTION_CHECKOUT_CREATE_FAILED: 'SUBSCRIPTION_CHECKOUT_CREATE_FAILED',
  SUBSCRIPTION_TIER_CHANGE_FAILED: 'SUBSCRIPTION_TIER_CHANGE_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
